# As a general rule, the latest release of Keras is compatible with the latest
# release of TensorFlow as well as the previous release of TensorFlow (in most
# cases, it is actually compatible with several prior TF releases, but that is
# not guaranteed).
#
# -- https://github.com/keras-team/keras/issues/10440#issuecomment-397428200

language: python

branches:
  only:
    - master
    - dev

env:
  - TENSORFLOW='tensorflow<2' KERAS='keras'

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      dist: xenial
      env: TENSORFLOW='tensorflow<2' KERAS='keras' INSTALL_FROM_SOURCE=1
    - os: linux
      python: 3.6
      env: TENSORFLOW='tensorflow<2' KERAS='keras' INSTALL_FROM_SOURCE=1
    - os: linux
      python: 3.5
      env: TENSORFLOW='tensorflow<2' KERAS='keras' INSTALL_FROM_SOURCE=1

install:
  - pip install $TENSORFLOW $KERAS
  - if [ -z $INSTALL_FROM_SOURCE ]; then
       pip install .;
    else
       pip install stardist;
    fi;

script:
  - pytest -v --durations=50 -m "not gpu";